version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432 # make sure you don't have another container running on 5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=citizix_user
      - POSTGRES_DB=citizix_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080